version: '2'
services:
    songshudatamiddleware-app:
        image: songshudatamiddleware
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://songshudatamiddleware-postgresql:5432/songshuDataMiddleware
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    songshudatamiddleware-postgresql:
        extends:
            file: postgresql.yml
            service: songshudatamiddleware-postgresql
